#file is named "travis.sample.yml".
# Rename it ".travis.yml".
# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "3.4"
addons:
  postgresql: "9.3"

sudo: 
  - required

services: postgresql

before_install:
  - sudo apt-get update
  - sudo apt-get install mysql-client
  - sudo apt-get install ufw
env:
  - DJANGO=1.8

install:
  - pip install --upgrade pip
  - pip install coverage
  - pip install requests
  - pip install psycopg2 --quiet
  - pip install django
  - pip3 install djangorestframework
  - pip3 install markdown
  - pip3 install django-filter
  - pip3 install mysqlclient
  - pip3 install sqlalchemy
  - pip3 install requests

before_script:
    - uname -a
    - printenv
    - pip3 --version
    - psql -c 'create database test;' -U postgres
    - psql -c 'CREATE ROLE lambda SUPERUSER CREATEDB CREATEROLE INHERIT LOGIN;' -U postgres
    - pip3 freeze
    - python3 --version
    - coverage3 --version
    

script:
    - date
    - ls -al
    - touch IDB.log
    - ls -al
    - make run_travis &
    - make migrate_travis
    - make test
    - ls -al
