# This file is named "travis.sample.yml".
# Rename it ".travis.yml".
# http://docs.travis-ci.com/user/build-configuration/

language: python

python:
    - "3.4"
addons:
  postgresql: "9.3"

sudo: 
  - required

before_install:
    - sudo apt-get update

env:
  - DJANGO=1.8

install:
    - pip install --upgrade pip
    - pip install coverage
    - sudo apt-get install python-numpy

before_script:
    - uname -a
    - printenv
    - pip3 --version
    - psql -c 'create database travis_ci_test;' -U postgres
    - pip3 freeze
    - python3 --version
    - coverage3 --version
    - python3 -c "import numpy; print(numpy.__version__)"

script:
    - date
    - ls -al
    - touch IDB.log
    - ls -al
    #- make test
    - ls -al
