FORMAT: 1A
HOST: http://8bytedining.me

# 8bytedining

8bytedining is a simple API allowing consumers to retreave information about recipes, cuisines, and ingredents.

# Group Recipes

Resources related to recipes in the API.


## Recipes [api/Recipes/{recipe_id}]

A recipe object has the following attributes:

+ Parameters
    + recipe_id: 1 (required, string, 'barley-risotto') ... String recipe_id of the recipe to perform action with. Has example value.

### Obtain a Recipe [GET]

+ Response 200 (application/json)

    [
      {
        "name": "Barley Risotto",
        "id": "barley-risotto",
        "url": "https://api.pearson.com/kitchen-manager/v1/recipes/barley-risotto",
        "cuisine": "Italian",
        "cooking_method": "Risotto method",
        "ingredients": [
        "barley",
        "water",
        "butter",
        "garlic clove",
        "Chicken Stock",
        "green onion",
        "asiago cheese",
        "kosher salt",
        "ground black pepper"
        ],
        "image": "https://api.pearson.com/kitchen-manager/v1/images/full/defaultrecipe.jpg",
        "thumb": "https://api.pearson.com/kitchen-manager/v1/images/thumbs/defaultrecipe.jpg"
       }
       { 
         "etc...."
        }
    ]

## Similar recipes [api/Recipes/?id={recipe_id}?]

A recipe object has the following attributes:

+ Parameters
    + id: 1 (required, number) - ID of the Question in form of an integer

### Obtain a Recipe [GET]

+ Response 200 (application/json)

    [
      {
        "name": "Barley Risotto",
        "id": "barley-risotto",
        "url": "https://api.pearson.com/kitchen-manager/v1/recipes/barley-risotto",
        "cuisine": "Italian",
        "cooking_method": "Risotto method",
        "ingredients": [
        "barley",
        "water",
        "butter",
        "garlic clove",
        "Chicken Stock",
        "green onion",
        "asiago cheese",
        "kosher salt",
        "ground black pepper"
        ],
        "image": "https://api.pearson.com/kitchen-manager/v1/images/full/defaultrecipe.jpg",
        "thumb": "https://api.pearson.com/kitchen-manager/v1/images/thumbs/defaultrecipe.jpg"
       }
       { 
         "etc...."
        }
    ]


# Group Ingredients

Resources related to ingredients in the API.

## Ingredients [api/ingredients/{ingredient_id}]

### Obtain an Ingredient [GET]

+ Response 200 (application/json)

    [
        {
            "ingredients": [
                "barley",
                "water",
                "butter",
                "garlic clove",
                "Chicken Stock",
                "green onion",
                "asiago cheese",
                "kosher salt",
                "ground black pepper"
      ]
        } , 
        {
         "more ingredients..."
        }
    ]

#Group Cusine

Resources related to ingredients in the API.

## Cusines [api/cusines/{cusinie_id}]

### Obtain a Cusine [GET]

+ Response 200 (application/json)

    [
      {
        "name": "African",
        "id": "african",
        "url": "https://api.pearson.com/kitchen-manager/v1/cuisines/african",
        "recipe_count": 0
      },
      {
        "more cusines..."
      }
    ]








